dist: xenial
install:
 - pip install -r requirements-travis.txt
language: python
python:
 - 3.5
 - 3.6
 - 3.7
 - 3.8-dev
script:
 - python --version
 - pip list
 - coverage run tests.py -a
 - flake8 pent
 - do_rest=$( echo $TRAVIS_PYTHON_VERSION | grep -e '^3\.6' | wc -l )
# - if [ $do_rest -gt 0 ]; then pip install black; black --check .; else echo "No black."; fi
# - if [ $do_rest -gt 0 ]; then sh -c 'cd doc; make doctest'; else echo "No doctest."; fi
 - if [ $do_rest -gt 0 ]; then codecov; else echo "No codecov."; fi

